
from panda3d.core import Vec3
import random

class Customer:
    def __init__(self, base, table):
        self.base = base
        self.table = table

        # Visual (Composition similar to player but different colors)
        self.model = self.base.render.attachNewNode("customer_root")

        self.body = self.base.loader.loadModel("models/box")
        self.body.reparentTo(self.model)
        self.body.setScale(0.6, 0.4, 0.8)
        self.body.setZ(0.4)
        self.body.setColor(random.random(), random.random(), random.random(), 1)

        self.head = self.base.loader.loadModel("models/smiley")
        self.head.reparentTo(self.model)
        self.head.setZ(1.1)
        self.head.setScale(0.25)

        # Start at "door"
        self.model.setPos(-10, -10, 0)
        self.target_pos = table.model.getPos() + Vec3(0, -1.5, 0)
        self.state = "walking_to_table"
        self.speed = 4.0
        self.order = None

    def update(self, dt):
        if self.state == "walking_to_table":
            diff = self.target_pos - self.model.getPos()
            if diff.length() < 0.1:
                self.state = "waiting_for_order"
                self.table.occupied_by = self
                # Order will be generated by OrderManager
            else:
                diff.normalize()
                self.model.setPos(self.model.getPos() + diff * self.speed * dt)

        elif self.state == "leaving":
            target = Vec3(-10, -10, 0)
            diff = target - self.model.getPos()
            if diff.length() < 0.1:
                self.destroy()
            else:
                diff.normalize()
                self.model.setPos(self.model.getPos() + diff * self.speed * dt)

    def leave(self):
        self.state = "leaving"
        if self.table:
            self.table.occupied_by = None

    def destroy(self):
        self.model.removeNode()
        if self in self.base.customers:
            self.base.customers.remove(self)
